[colors.primary]
background = "#120812"
foreground = "#c3c1c3"

[colors.normal]
black = "#120812"
red = "#921832"
green = "#9B2E50"
yellow = "#D13763"
blue = "#A24E6A"
magenta = "#A3717C"
cyan = "#C26494"
white = "#c3c1c3"

[colors.bright]
black = "#6a576a"
red = "#921832"
green = "#9B2E50"
yellow = "#D13763"
blue = "#A24E6A"
magenta = "#A3717C"
cyan = "#C26494"
white = "#c3c1c3"

[font.normal]
family = "MesloLGS NF"
