[colors.primary]
background = "#242b36"
foreground = "#c8cacc"

[colors.normal]
black = "#242b36"
red = "#8D99A8"
green = "#A6BAC6"
yellow = "#D5BCC3"
blue = "#C9D2DD"
magenta = "#E9D6DE"
cyan = "#D1D9E2"
white = "#c8cacc"

[colors.bright]
black = "#6a7481"
red = "#8D99A8"
green = "#A6BAC6"
yellow = "#D5BCC3"
blue = "#C9D2DD"
magenta = "#E9D6DE"
cyan = "#D1D9E2"
white = "#c8cacc"

[font.normal]
family = "MesloLGS NF"
