[colors.primary]
background = "#150f09"
foreground = "#c4c3c1"

[colors.normal]
black = "#150f09"
red = "#3D3C44"
green = "#635751"
yellow = "#8B7563"
blue = "#9F8976"
magenta = "#797787"
cyan = "#BDAD9F"
white = "#c4c3c1"

[colors.bright]
black = "#6c6358"
red = "#3D3C44"
green = "#635751"
yellow = "#8B7563"
blue = "#9F8976"
magenta = "#797787"
cyan = "#BDAD9F"
white = "#c4c3c1"

[font.normal]
family = "MesloLGS NF"
